# Generated by Django 5.2.12 on 2026-03-09 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='return_date',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='issue_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuebook',
            name='return_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
