# Generated by Django 5.2.12 on 2026-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_issuebook_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='flb_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
